# Generated by Django 4.2.7 on 2023-12-01 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_data',
            field=models.CharField(default=django.utils.timezone.now, max_length=545),
        ),
    ]
