# Generated by Django 4.2.7 on 2023-12-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_tag_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('100 TO 1000', '100 TO 1000'), ('1000 TO 2000', '1000 TO 2000'), ('2000 TO 3000', '2000 TO 3000'), ('3000 TO 4000', '3000 TO 4000'), ('4000 TO 5000', '4000 TO 5000')], max_length=60),
        ),
    ]
