# Generated by Django 4.2.7 on 2023-12-01 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_filter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, default=uuid.UUID('1e5c248e-6736-48f6-b90a-0ac305997f79'), max_length=100, null=True, unique=True),
        ),
    ]
