# Generated by Django 4.2.7 on 2023-12-02 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_product_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, default=uuid.UUID('c0d56a35-2e96-471d-8988-a1c39c0a5406'), max_length=100, null=True, unique=True),
        ),
    ]
