# Generated by Django 4.2.7 on 2023-12-02 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_alter_product_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, default=uuid.UUID('c22b157d-e89d-47cc-9b05-d652987c2c4e'), max_length=100, null=True, unique=True),
        ),
    ]
