# Generated by Django 4.2.6 on 2023-12-03 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_alter_product_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'PUBLIC'), ('DRAFT', 'DRAFT')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, default=uuid.UUID('fd68d874-ec79-4cbf-b24b-c092f72d4fd3'), max_length=100, null=True, unique=True),
        ),
    ]
