# Generated by Django 4.2.7 on 2023-12-06 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_alter_product_status_alter_product_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, default=uuid.UUID('5f3343f6-fa38-44bb-b6ae-ce5a4104f06d'), max_length=100, null=True, unique=True),
        ),
    ]
